// lib/ui_strings.dart
// Simple localization system keyed by language code.
// Falls back to English if a key or language is missing.

import 'package:easy_localization/easy_localization.dart';
import 'package:flutter/material.dart';

const Map<String, Map<String, String>> _strings = {
  // ─── English ──────────────────────────────────────────────────────────────
  'en': {
    'selectLanguage': 'Select Your Language',
    'selectLanguageDesc':
        'Choose the language you speak\nto personalize your experience.',
    'continue': 'Continue',
    'welcomeTo': 'Welcome to Salearn',
    'setupApiKey':
        'Set up your API key, then we\'ll find your\nlanguage level to personalize your experience.',
    'step1ApiKey': 'Activation Code',
    'apiKeyVerified': 'API Key Verified',
    'apiKeyRequired': 'Required to power AI features',
    'pasteApiKey': 'Paste your activation code…',
    'validateSave': 'Validate & Save',
    'ready': '✓ Ready',
    'howToGetKey': 'How to get your API Key?',
    'helpStep1': 'Visit Google AI Studio',
    'helpStep2': 'Log in with your Google account',
    'helpStep3': 'Click "Create API Key" and copy it',
    'playTutorial': 'Play Tutorial',
    'takeTest': 'Take the Placement Test',
    'testDesc': '10 adaptive MCQ questions · ~4 min',
    'testDescLong':
        'AI-generated multiple choice questions that adapt to your answers. Your exact CEFR level will be determined automatically.',
    'orChooseManually': 'OR CHOOSE MANUALLY',
    'selectYourLevel': 'Select Your Level',
    'pleaseValidateKey': '⚠ Please validate your API key first.',
    'pleaseEnterKey': 'Please enter your API key.',
    // Dashboard
    'goodMorning': 'Good Morning',
    'goodAfternoon': 'Good Afternoon',
    'goodEvening': 'Good Evening',
    'lateSession': 'Ready for a late session?',
    'letsPractice': "Let's practice",
    'youAreAtLevel': 'You are at level',
    'change': 'Change',
    'whatToTalkAbout': 'What would you like to talk about?',
    'startLearning': 'Start Learning',
    // Test
    'placementTest': 'Placement Test',
    'question': 'Question',
    'of': 'of',
    'generatingQuestion': 'Generating question…',
    'analyzingProficiency': 'Analyzing your proficiency…',
    'tryAgain': 'Try Again',
    'submitGetResults': 'Submit & Get Results',
    'nextQuestion': 'Next Question →',
    'yourLevel': 'Your Level',
    'correct': 'correct',
    'startLearningArrow': 'Start Learning →',
    // Main
    'typeAnswer': 'Type your answer…',
    'submit': 'Submit',
    'feedback': 'Feedback',
    'examples': 'Examples & Expressions',
    'translate': 'Translate',
    'translation': 'Translation',
    // Drawer
    'proficiency': 'PROFICIENCY',
    'changeLevel': 'Change Level',
    'languages': 'LANGUAGES',
    'iSpeak': 'My language',
    'iWantToLearn': 'I want to learn',
    'topics': 'TOPICS',
    'apiKeySetup': 'ACTIVATION CODE',
    'testAndSave': 'Test & Save',
    'selectNativeLanguage': 'Which language do you speak?',
    'selectNativeLanguageDesc': 'Your interface will switch to this language.',
    'selectTargetLanguage': 'Which language do you want to learn?',
    'selectTargetLanguageDesc':
        'AI exercises will be generated in this language.',
    'translateOrAnswer': 'Translate or Answer',
    'topicLabel': 'Topic',
    'configureApiKeyFirst': 'Please enter your activation code first.',
    'aiLanguageTutor': 'AI Language Tutor',
    'couldNotOpenLink': 'Could not open link.',
    'appName': 'SaLearn',
    'homeTab': 'Home',
    'exercisesTab': 'Exercises',
    'progressTab': 'Progress',
    'profileTab': 'Profile',
    'overview': 'Overview',
    'startPracticing': 'Start Practicing',
    'learnWordsThroughContext': 'Learn words through context',
    'nextSentence': 'Next Sentence',
    'newWord': 'New Word',
    'zeroToHero': 'Zero to Hero',
    'dailyGoal': 'Daily Goal',
    'exercisesDone': 'Exercises Done',
    'skillCategories': 'Skill Categories',
    'sayThisSentence': 'Say this sentence:',
    'holdToSpeak': 'Hold to speak',
    'releaseToCheck': 'Release to check',
    'youSaid': 'You said:',
    'greatPronunciation': 'Great pronunciation!',
    'keepPracticing': 'Keep practicing',
    'accuracy': 'Accuracy',
    'newSentence': 'New Sentence',
    'typeWhatYouHeard': 'Type what you heard...',
    'tapToPlay': 'Tap to play audio',
    'playing': 'Playing...',
    'checkAnswer': 'Check Answer',
    'theSentenceWas': 'The sentence was:',
    'selectOption': 'Select an option',
    'grammarRule': 'Grammar Rule:',
    'findTheError': 'Find the Error',
    'fillInBlank': 'Fill in the Blank',
    'chooseCorrectOption': 'Choose the correct option:',
    'startExercise': 'Start Exercise',
    'grammarPractice': 'Grammar Practice',
    'grammarDesc':
        'Test your grammar with error correction\nand fill-in-the-blank exercises.',
    'vocabQuestion': 'What does this word mean?',
    'nextWord': 'Next Word',
    'readingPassage': 'Reading Passage',
    'nextPassage': 'Next Passage',
    'noExercises': 'No exercises yet. Start practicing!',
    'vocabulary': 'Vocabulary',
    'writing': 'Writing',
    'grammar': 'Grammar',
    'reading': 'Reading',
    'listening': 'Listening',
    'speaking': 'Speaking',
    'correction': 'Correction',
    'fillBlank': 'Fill Blank',
    'streak': 'Day Streak',
    'beginner': 'Beginner',
    'practice': 'Practice',
    'ielts': 'Exams',
    'categories': 'Categories',
    'sameLanguageWarning': 'Native and target languages cannot be the same.',
    'noInternetConnection': 'No internet connection',
    'checkConnectionAndRetry': 'Check your connection and try again',
    'errorOccurred': 'An error occurred. Please try again.',
  },
  // ─── Arabic ───────────────────────────────────────────────────────────────
  'ar': {
    'selectLanguage': 'اختر لغتك',
    'selectLanguageDesc': 'اختر اللغة التي تتحدثها\nلتخصيص تجربتك.',
    'continue': 'متابعة',
    'welcomeTo': 'مرحبًا بك في Salearn',
    'setupApiKey':
        'أدخل كود التفعيل الخاص بك، ثم سنحدد\nمستوى لغتك لتخصيص تجربتك.',
    'step1ApiKey': 'الخطوة 1: كود التفعيل',
    'apiKeyVerified': 'تم التحقق من الكود',
    'apiKeyRequired': 'مطلوب لتشغيل ميزات الذكاء الاصطناعي',
    'pasteApiKey': 'أدخل كود التفعيل هنا…',
    'validateSave': 'تحقق واحفظ',
    'ready': '✓ جاهز',
    'howToGetKey': 'كيف تحصل على كود التفعيل؟',
    'helpStep1': 'قم بزيارة Google AI Studio',
    'helpStep2': 'سجل الدخول بحساب Google الخاص بك',
    'helpStep3': 'اضغط "إنشاء كود تفعيل" وانسخه',
    'playTutorial': 'شاهد البرنامج التعليمي',
    'takeTest': 'قم باختبار المستوى',
    'testDesc': '10 أسئلة اختيار من متعدد · ~4 دقائق',
    'testDescLong':
        'أسئلة اختيار من متعدد تم إنشاؤها بواسطة الذكاء الاصطناعي تتكيف مع إجاباتك. سيتم تحديد مستواك الدقيق في CEFR تلقائيًا.',
    'orChooseManually': 'أو اختر يدويًا',
    'selectYourLevel': 'اختر مستواك',
    'pleaseValidateKey': '⚠ يرجى التحقق من كود التفعيل أولاً.',
    'pleaseEnterKey': 'يرجى إدخال كود التفعيل.',
    'goodMorning': 'صباح الخير',
    'goodAfternoon': 'مساء الخير',
    'goodEvening': 'مساء الخير',
    'lateSession': 'جلسة متأخرة؟',
    'letsPractice': 'هيا نتمرن على',
    'youAreAtLevel': 'أنت في المستوى',
    'change': 'تغيير',
    'whatToTalkAbout': 'عن ماذا تريد التحدث؟',
    'startLearning': 'ابدأ التعلم',
    'placementTest': 'اختبار تحديد المستوى',
    'question': 'سؤال',
    'of': 'من',
    'generatingQuestion': 'جاري إنشاء السؤال…',
    'analyzingProficiency': 'جاري تحليل مستواك…',
    'tryAgain': 'حاول مجددًا',
    'submitGetResults': 'إرسال والنتائج',
    'nextQuestion': 'السؤال التالي →',
    'yourLevel': 'مستواك',
    'correct': 'صحيح',
    'startLearningArrow': 'ابدأ التعلم →',
    'typeAnswer': 'اكتب إجابتك…',
    'submit': 'إرسال',
    'feedback': 'التقييم',
    'examples': 'أمثلة وتعبيرات',
    'translate': 'ترجمة',
    'translation': 'ترجمة',
    'proficiency': 'المستوى',
    'changeLevel': 'تغيير المستوى',
    'languages': 'اللغات',
    'iSpeak': 'لغتي',
    'iWantToLearn': 'أريد تعلم',
    'topics': 'المواضيع',
    'apiKeySetup': 'كود التفعيل',
    'testAndSave': 'اختبر واحفظ',
    'selectNativeLanguage': 'ما هي لغتك الأم؟',
    'selectNativeLanguageDesc': 'ستتحول واجهة التطبيق إلى هذه اللغة.',
    'selectTargetLanguage': 'ما هي اللغة التي تريد تعلمها؟',
    'selectTargetLanguageDesc':
        'سيتم إنشاء تمارين الذكاء الاصطناعي بهذه اللغة.',
    'translateOrAnswer': 'ترجم أو أجب',
    'topicLabel': 'الموضوع',
    'configureApiKeyFirst': 'يرجى إدخال كود التفعيل أولاً.',
    'aiLanguageTutor': 'مدرّس لغات بالذكاء الاصطناعي',
    'couldNotOpenLink': 'تعذّر فتح الرابط.',
    'appName': 'SaLearn',
    'homeTab': 'الرئيسية',
    'exercisesTab': 'التمارين',
    'progressTab': 'التقدم',
    'profileTab': 'الملف الشخصي',
    'overview': 'نظرة عامة',
    'startPracticing': 'ابدأ التدرب',
    'learnWordsThroughContext': 'تعلم الكلمات من خلال السياق',
    'nextSentence': 'الجملة التالية',
    'newWord': 'كلمة جديدة',
    'zeroToHero': 'من الصفر إلى البطولة',
    'dailyGoal': 'الهدف اليومي',
    'exercisesDone': 'التمارين المنجزة',
    'skillCategories': 'تصنيفات المهارات',
    'sayThisSentence': 'قل هذه الجملة:',
    'holdToSpeak': 'اضغط للتحدث',
    'releaseToCheck': 'أفلص للتحقق',
    'youSaid': 'قلت:',
    'greatPronunciation': 'نطق رائع!',
    'keepPracticing': 'استمر في الممارسة',
    'accuracy': 'الدقة',
    'newSentence': 'جملة جديدة',
    'typeWhatYouHeard': 'اكتب ما سمعته...',
    'tapToPlay': 'اضغط لتشغيل الصوت',
    'playing': 'جارٍ التشغيل...',
    'checkAnswer': 'تحقق من الإجابة',
    'theSentenceWas': 'الجملة كانت:',
    'selectOption': 'اختر خياراً',
    'grammarRule': 'قاعدة نحوية:',
    'findTheError': 'ابحث عن الخطأ',
    'fillInBlank': 'املأ الفراغ',
    'chooseCorrectOption': 'اختر الخيار الصحيح:',
    'startExercise': 'ابدأ التمرين',
    'grammarPractice': 'تمرين القواعد',
    'grammarDesc': 'اختبر قواعدك اللغوية من خلال\nتصحيح الأخطاء وملء الفراغات.',
    'vocabQuestion': 'ماذا تعني هذه الكلمة؟',
    'nextWord': 'الكلمة التالية',
    'readingPassage': 'نص القراءة',
    'nextPassage': 'النص التالي',
    'noExercises': 'لا توجد تمارين بعد. ابدأ بالتدرب!',
    'vocabulary': 'المفردات',
    'writing': 'الكتابة',
    'grammar': 'القواعد',
    'reading': 'القراءة',
    'listening': 'الاستماع',
    'speaking': 'التحدث',
    'correction': 'تصحيح',
    'fillBlank': 'املأ الفراغ',
    'streak': 'أيام متتالية',
    'beginner': 'مبتدئ',
    'practice': 'تمرين',
    'ielts': 'IELTS',
    'categories': 'التصنيفات',
  },
  // ─── French ───────────────────────────────────────────────────────────────
  'fr': {
    'selectLanguage': 'Choisissez votre langue',
    'selectLanguageDesc':
        'Choisissez la langue que vous parlez\npour personnaliser votre expérience.',
    'continue': 'Continuer',
    'welcomeTo': 'Bienvenue sur Salearn',
    'setupApiKey':
        'Configurez votre clé API, puis nous trouverons\nvotre niveau pour personnaliser votre expérience.',
    'step1ApiKey': 'Étape 1 : Clé API',
    'apiKeyVerified': 'Clé API vérifiée',
    'apiKeyRequired': 'Nécessaire pour les fonctionnalités IA',
    'pasteApiKey': 'Collez votre clé API Gemini…',
    'validateSave': 'Valider et enregistrer',
    'ready': '✓ Prêt',
    'howToGetKey': 'Comment obtenir votre clé API ?',
    'helpStep1': 'Visitez Google AI Studio',
    'helpStep2': 'Connectez-vous avec votre compte Google',
    'helpStep3': 'Cliquez "Créer une clé API" et copiez-la',
    'playTutorial': 'Voir le tutoriel',
    'takeTest': 'Passer le test de placement',
    'testDesc': '10 questions adaptatives · ~4 min',
    'testDescLong':
        'Questions à choix multiples générées par IA qui s\'adaptent à vos réponses. Votre niveau CECR sera déterminé automatiquement.',
    'orChooseManually': 'OU CHOISIR MANUELLEMENT',
    'selectYourLevel': 'Sélectionnez votre niveau',
    'pleaseValidateKey': '⚠ Veuillez d\'abord valider votre clé API.',
    'pleaseEnterKey': 'Veuillez entrer votre clé API.',
    'goodMorning': 'Bonjour',
    'goodAfternoon': 'Bon après-midi',
    'goodEvening': 'Bonsoir',
    'lateSession': 'Session tardive ?',
    'letsPractice': 'Pratiquons',
    'youAreAtLevel': 'Vous êtes au niveau',
    'change': 'Modifier',
    'whatToTalkAbout': 'De quoi voulez-vous parler ?',
    'startLearning': 'Commencer',
    'placementTest': 'Test de niveau',
    'question': 'Question',
    'of': 'sur',
    'generatingQuestion': 'Génération de la question…',
    'analyzingProficiency': 'Analyse de votre niveau…',
    'tryAgain': 'Réessayer',
    'submitGetResults': 'Soumettre et résultats',
    'nextQuestion': 'Question suivante →',
    'yourLevel': 'Votre niveau',
    'correct': 'correct',
    'startLearningArrow': 'Commencer →',
    'typeAnswer': 'Tapez votre réponse…',
    'submit': 'Envoyer',
    'feedback': 'Retour',
    'examples': 'Exemples et expressions',
    'translate': 'Traduire',
    'translation': 'Traduction',
    'proficiency': 'NIVEAU',
    'changeLevel': 'Changer le niveau',
    'languages': 'LANGUES',
    'iSpeak': 'Ma langue',
    'iWantToLearn': 'Je veux apprendre',
    'topics': 'SUJETS',
    'apiKeySetup': 'CLÉ API',
    'testAndSave': 'Tester et sauver',
    'selectNativeLanguage': 'Quelle langue parlez-vous ?',
    'selectNativeLanguageDesc': "L'interface passera dans cette langue.",
    'selectTargetLanguage': 'Quelle langue voulez-vous apprendre ?',
    'selectTargetLanguageDesc':
        'Les exercices IA seront générés dans cette langue.',
    'translateOrAnswer': 'Traduire ou répondre',
    'topicLabel': 'Sujet',
    'configureApiKeyFirst': "Veuillez d'abord configurer votre clé API.",
    'aiLanguageTutor': 'Tuteur de langues IA',
    'couldNotOpenLink': 'Impossible d\'ouvrir le lien.',
  },
  // ─── Spanish ──────────────────────────────────────────────────────────────
  'es': {
    'selectLanguage': 'Elige tu idioma',
    'selectLanguageDesc':
        'Elige el idioma que hablas\npara personalizar tu experiencia.',
    'continue': 'Continuar',
    'welcomeTo': 'Bienvenido a Salearn',
    'setupApiKey':
        'Configura tu clave API, luego encontraremos\ntu nivel para personalizar tu experiencia.',
    'step1ApiKey': 'Paso 1: Clave API',
    'apiKeyVerified': 'Clave API verificada',
    'apiKeyRequired': 'Necesario para funciones de IA',
    'pasteApiKey': 'Pega tu clave API de Gemini…',
    'validateSave': 'Validar y guardar',
    'ready': '✓ Listo',
    'howToGetKey': '¿Cómo obtener tu clave API?',
    'helpStep1': 'Visita Google AI Studio',
    'helpStep2': 'Inicia sesión con tu cuenta de Google',
    'helpStep3': 'Haz clic en "Crear clave API" y cópiala',
    'playTutorial': 'Ver tutorial',
    'takeTest': 'Hacer el test de nivel',
    'testDesc': '10 preguntas adaptativas · ~4 min',
    'testDescLong':
        'Preguntas de opción múltiple generadas por IA que se adaptan a tus respuestas. Tu nivel MCER se determinará automáticamente.',
    'orChooseManually': 'O ELEGIR MANUALMENTE',
    'selectYourLevel': 'Selecciona tu nivel',
    'pleaseValidateKey': '⚠ Por favor valida tu clave API primero.',
    'pleaseEnterKey': 'Por favor ingresa tu clave API.',
    'goodMorning': 'Buenos días',
    'goodAfternoon': 'Buenas tardes',
    'goodEvening': 'Buenas noches',
    'lateSession': '¿Sesión nocturna?',
    'letsPractice': 'Practiquemos',
    'youAreAtLevel': 'Estás en el nivel',
    'change': 'Cambiar',
    'whatToTalkAbout': '¿De qué quieres hablar?',
    'startLearning': 'Empezar',
    'placementTest': 'Test de nivel',
    'question': 'Pregunta',
    'of': 'de',
    'generatingQuestion': 'Generando pregunta…',
    'analyzingProficiency': 'Analizando tu nivel…',
    'tryAgain': 'Intentar de nuevo',
    'submitGetResults': 'Enviar y resultados',
    'nextQuestion': 'Siguiente →',
    'yourLevel': 'Tu nivel',
    'correct': 'correcto',
    'startLearningArrow': 'Empezar →',
    'typeAnswer': 'Escribe tu respuesta…',
    'submit': 'Enviar',
    'feedback': 'Comentarios',
    'examples': 'Ejemplos y expresiones',
    'translate': 'Traducir',
    'translation': 'Traducción',
    'proficiency': 'NIVEL',
    'changeLevel': 'Cambiar nivel',
    'languages': 'IDIOMAS',
    'iSpeak': 'Mi idioma',
    'iWantToLearn': 'Quiero aprender',
    'topics': 'TEMAS',
    'apiKeySetup': 'CLAVE API',
    'testAndSave': 'Probar y guardar',
    'selectNativeLanguage': '¿Qué idioma hablas?',
    'selectNativeLanguageDesc': 'La interfaz cambiará a este idioma.',
    'selectTargetLanguage': '¿Qué idioma quieres aprender?',
    'selectTargetLanguageDesc':
        'Los ejercicios de IA se generarán en este idioma.',
    'translateOrAnswer': 'Traducir o responder',
    'topicLabel': 'Tema',
    'configureApiKeyFirst': 'Por favor configura tu clave API primero.',
    'aiLanguageTutor': 'Tutor de idiomas IA',
    'couldNotOpenLink': 'No se pudo abrir el enlace.',
  },
  // ─── Turkish ──────────────────────────────────────────────────────────────
  'tr': {
    'selectLanguage': 'Dilinizi seçin',
    'selectLanguageDesc':
        'Deneyiminizi kişiselleştirmek için\nkonuştuğunuz dili seçin.',
    'continue': 'Devam',
    'welcomeTo': 'Salearn\'e hoş geldiniz',
    'setupApiKey':
        'API anahtarınızı girin, ardından deneyiminizi\nkişiselleştirmek için seviyenizi belirleyelim.',
    'step1ApiKey': 'Adım 1: API Anahtarı',
    'apiKeyVerified': 'API Anahtarı doğrulandı',
    'apiKeyRequired': 'Yapay zeka özellikleri için gerekli',
    'pasteApiKey': 'Gemini API anahtarınızı yapıştırın…',
    'validateSave': 'Doğrula ve kaydet',
    'ready': '✓ Hazır',
    'howToGetKey': 'API anahtarı nasıl alınır?',
    'helpStep1': 'Google AI Studio\'yu ziyaret edin',
    'helpStep2': 'Google hesabınızla giriş yapın',
    'helpStep3': '"API Anahtarı Oluştur"a tıklayın ve kopyalayın',
    'playTutorial': 'Öğreticiyi izle',
    'takeTest': 'Seviye testini yapın',
    'testDesc': '10 uyarlanabilir soru · ~4 dk',
    'testDescLong':
        'Cevaplarınıza göre uyarlanan yapay zeka üretimi çoktan seçmeli sorular. CEFR seviyeniz otomatik olarak belirlenecektir.',
    'orChooseManually': 'VEYA MANUEL SEÇİN',
    'selectYourLevel': 'Seviyenizi seçin',
    'pleaseValidateKey': '⚠ Lütfen önce API anahtarınızı doğrulayın.',
    'pleaseEnterKey': 'Lütfen API anahtarınızı girin.',
    'goodMorning': 'Günaydın',
    'goodAfternoon': 'İyi öğleden sonra',
    'goodEvening': 'İyi akşamlar',
    'lateSession': 'Gece çalışması mı?',
    'letsPractice': 'Hadi pratik yapalım',
    'youAreAtLevel': 'Seviyeniz',
    'change': 'Değiştir',
    'whatToTalkAbout': 'Ne hakkında konuşmak istersiniz?',
    'startLearning': 'Öğrenmeye başla',
    'placementTest': 'Seviye testi',
    'question': 'Soru',
    'of': '/',
    'generatingQuestion': 'Soru oluşturuluyor…',
    'analyzingProficiency': 'Seviyeniz analiz ediliyor…',
    'tryAgain': 'Tekrar dene',
    'submitGetResults': 'Gönder ve sonuçlar',
    'nextQuestion': 'Sonraki →',
    'yourLevel': 'Seviyeniz',
    'correct': 'doğru',
    'startLearningArrow': 'Başla →',
    'typeAnswer': 'Cevabınızı yazın…',
    'submit': 'Gönder',
    'feedback': 'Geri bildirim',
    'examples': 'Örnekler ve ifadeler',
    'translate': 'Çevir',
    'translation': 'Çeviri',
    'proficiency': 'SEVİYE',
    'changeLevel': 'Seviye değiştir',
    'languages': 'DİLLER',
    'iSpeak': 'Dilim',
    'iWantToLearn': 'Öğrenmek istiyorum',
    'topics': 'KONULAR',
    'apiKeySetup': 'API ANAHTARI',
    'testAndSave': 'Test et ve kaydet',
    'selectNativeLanguage': 'Hangi dili konuşuyorsunuz?',
    'selectNativeLanguageDesc': 'Arayüz bu dile geçecektir.',
    'selectTargetLanguage': 'Hangi dili öğrenmek istiyorsunuz?',
    'selectTargetLanguageDesc':
        'Yapay zeka alıştırmaları bu dilde oluşturulacaktır.',
    'translateOrAnswer': 'Çevir veya cevapla',
    'topicLabel': 'Konu',
    'configureApiKeyFirst': 'Lütfen önce API anahtarınızı yapılandırın.',
    'aiLanguageTutor': 'Yapay Zeka Dil Öğretmeni',
    'couldNotOpenLink': 'Bağlantı açılamadı.',
  },
  // ─── German ───────────────────────────────────────────────────────────────
  'de': {
    'selectLanguage': 'Wählen Sie Ihre Sprache',
    'selectLanguageDesc':
        'Wählen Sie Ihre Sprache,\num Ihr Erlebnis zu personalisieren.',
    'continue': 'Weiter',
    'welcomeTo': 'Willkommen bei Salearn',
    'setupApiKey':
        'Richten Sie Ihren API-Schlüssel ein, dann\nbestimmen wir Ihr Niveau.',
    'step1ApiKey': 'Schritt 1: API-Schlüssel',
    'apiKeyVerified': 'API-Schlüssel verifiziert',
    'apiKeyRequired': 'Erforderlich für KI-Funktionen',
    'pasteApiKey': 'Gemini API-Schlüssel einfügen…',
    'validateSave': 'Überprüfen & speichern',
    'ready': '✓ Bereit',
    'howToGetKey': 'Wie erhalte ich einen API-Schlüssel?',
    'helpStep1': 'Besuchen Sie Google AI Studio',
    'helpStep2': 'Melden Sie sich mit Google an',
    'helpStep3': 'Klicken Sie "API-Schlüssel erstellen" und kopieren',
    'playTutorial': 'Tutorial ansehen',
    'takeTest': 'Einstufungstest machen',
    'testDesc': '10 adaptive Fragen · ~4 Min',
    'testDescLong':
        'KI-generierte Multiple-Choice-Fragen, die sich an Ihre Antworten anpassen. Ihr GER-Niveau wird automatisch bestimmt.',
    'orChooseManually': 'ODER MANUELL WÄHLEN',
    'selectYourLevel': 'Wählen Sie Ihr Niveau',
    'pleaseValidateKey': '⚠ Bitte überprüfen Sie zuerst Ihren API-Schlüssel.',
    'pleaseEnterKey': 'Bitte geben Sie Ihren API-Schlüssel ein.',
    'goodMorning': 'Guten Morgen',
    'goodAfternoon': 'Guten Tag',
    'goodEvening': 'Guten Abend',
    'lateSession': 'Späte Sitzung?',
    'letsPractice': 'Lass uns üben',
    'youAreAtLevel': 'Ihr Niveau ist',
    'change': 'Ändern',
    'whatToTalkAbout': 'Worüber möchten Sie sprechen?',
    'startLearning': 'Starten',
    'placementTest': 'Einstufungstest',
    'question': 'Frage',
    'of': 'von',
    'generatingQuestion': 'Frage wird generiert…',
    'analyzingProficiency': 'Analysiere Ihr Niveau…',
    'tryAgain': 'Erneut versuchen',
    'submitGetResults': 'Absenden & Ergebnisse',
    'nextQuestion': 'Nächste →',
    'yourLevel': 'Ihr Niveau',
    'correct': 'richtig',
    'startLearningArrow': 'Starten →',
    'typeAnswer': 'Antwort eingeben…',
    'submit': 'Senden',
    'feedback': 'Rückmeldung',
    'examples': 'Beispiele und Ausdrücke',
    'translate': 'Übersetzen',
    'translation': 'Übersetzung',
    'proficiency': 'NIVEAU',
    'changeLevel': 'Niveau ändern',
    'languages': 'SPRACHEN',
    'iSpeak': 'Meine Sprache',
    'iWantToLearn': 'Ich will lernen',
    'topics': 'THEMEN',
    'apiKeySetup': 'API-SCHLÜSSEL',
    'testAndSave': 'Testen & speichern',
    'selectNativeLanguage': 'Welche Sprache sprechen Sie?',
    'selectNativeLanguageDesc':
        'Die Oberfläche wird in diese Sprache wechseln.',
    'selectTargetLanguage': 'Welche Sprache möchten Sie lernen?',
    'selectTargetLanguageDesc': 'KI-Übungen werden in dieser Sprache erstellt.',
    'translateOrAnswer': 'Übersetzen oder antworten',
    'topicLabel': 'Thema',
    'configureApiKeyFirst':
        'Bitte konfigurieren Sie zuerst Ihren API-Schlüssel.',
    'aiLanguageTutor': 'KI-Sprachlehrer',
    'couldNotOpenLink': 'Link konnte nicht geöffnet werden.',
  },
  // ─── Italian ──────────────────────────────────────────────────────────────
  'it': {
    'selectLanguage': 'Seleziona la tua lingua',
    'selectLanguageDesc':
        'Scegli la lingua che parli\nper personalizzare la tua esperienza.',
    'continue': 'Continua',
    'welcomeTo': 'Benvenuto in Salearn',
    'setupApiKey':
        'Imposta la tua chiave API, poi troveremo il tuo\nlivello per personalizzare l\'esperienza.',
    'step1ApiKey': 'Passo 1: Chiave API',
    'apiKeyVerified': 'Chiave API verificata',
    'apiKeyRequired': 'Richiesto per le funzioni IA',
    'pasteApiKey': 'Incolla la tua chiave Gemini API…',
    'validateSave': 'Convalida & Salva',
    'ready': '✓ Pronto',
    'howToGetKey': 'Come ottenere la chiave API?',
    'helpStep1': 'Visita Google AI Studio',
    'helpStep2': 'Accedi con l\'account Google',
    'helpStep3': 'Clicca "Create API Key" e copiala',
    'playTutorial': 'Guarda il tutorial',
    'takeTest': 'Fai il test di livello',
    'testDesc': '10 domande a scelta multipla · ~4 min',
    'testDescLong':
        'Domande a scelta multipla generate dall\'IA che si adattano alle tue risposte. Il tuo livello CEFR esatto verrà determinato automaticamente.',
    'orChooseManually': 'OPPURE SCEGLI MANUALMENTE',
    'selectYourLevel': 'Seleziona il tuo livello',
    'pleaseValidateKey': '⚠ Convalida prima la tua chiave API.',
    'pleaseEnterKey': 'Inserisci la tua chiave API.',
    'goodMorning': 'Buongiorno',
    'goodAfternoon': 'Buon Pomeriggio',
    'goodEvening': 'Buonasera',
    'lateSession': 'Pronto per una sessione serale?',
    'letsPractice': "Facciamo pratica",
    'youAreAtLevel': 'Sei al livello',
    'change': 'Cambia',
    'whatToTalkAbout': 'Di cosa vorresti parlare?',
    'startLearning': 'Inizia a imparare',
    'placementTest': 'Test di posizionamento',
    'question': 'Domanda',
    'of': 'di',
    'generatingQuestion': 'Generazione domanda…',
    'analyzingProficiency': 'Analisi della tua competenza…',
    'tryAgain': 'Riprova',
    'submitGetResults': 'Invia e ottieni i risultati',
    'nextQuestion': 'Prossima Domanda →',
    'yourLevel': 'Il tuo livello',
    'correct': 'corrette',
    'startLearningArrow': 'Inizia a imparare →',
    'typeAnswer': 'Scrivi la tua risposta…',
    'submit': 'Invia',
    'feedback': 'Feedback',
    'examples': 'Esempi ed espressioni',
    'translate': 'Traduci',
    'translation': 'Traduzione',
    'proficiency': 'COMPETENZA',
    'changeLevel': 'Cambia Livello',
    'languages': 'LINGUE',
    'iSpeak': 'La mia lingua',
    'iWantToLearn': 'Voglio imparare',
    'topics': 'ARGOMENTI',
    'apiKeySetup': 'CHIAVE API',
    'testAndSave': 'Testa & Salva',
    'selectNativeLanguage': 'Quale lingua parli?',
    'selectNativeLanguageDesc': 'La tua interfaccia passerà a questa lingua.',
    'selectTargetLanguage': 'Quale lingua vuoi imparare?',
    'selectTargetLanguageDesc':
        'Gli esercizi dell\'IA saranno generati in questa lingua.',
    'translateOrAnswer': 'Traduci o Rispondi',
    'topicLabel': 'Argomento',
    'configureApiKeyFirst': 'Configura prima la tua chiave API.',
    'aiLanguageTutor': 'Tutor Linguistico IA',
    'couldNotOpenLink': 'Impossibile aprire il link.',
  },
  // ─── Portuguese ───────────────────────────────────────────────────────────
  'pt': {
    'selectLanguage': 'Selecione seu idioma',
    'selectLanguageDesc':
        'Escolha o idioma que você fala\npara personalizar sua experiência.',
    'continue': 'Continuar',
    'welcomeTo': 'Bem-vindo ao Salearn',
    'setupApiKey':
        'Configure sua chave API, então encontraremos seu\nnível para personalizar sua experiência.',
    'step1ApiKey': 'Passo 1: Chave API',
    'apiKeyVerified': 'Chave API verificada',
    'apiKeyRequired': 'Necessário para recursos de IA',
    'pasteApiKey': 'Cole sua chave Gemini API…',
    'validateSave': 'Validar e Salvar',
    'ready': '✓ Pronto',
    'howToGetKey': 'Como obter sua chave API?',
    'helpStep1': 'Visite o Google AI Studio',
    'helpStep2': 'Faça login com sua conta Google',
    'helpStep3': 'Clique em "Criar chave API" e copie-a',
    'playTutorial': 'Assistir ao tutorial',
    'takeTest': 'Fazer Teste de Nivelamento',
    'testDesc': '10 questões de múltipla escolha · ~4 min',
    'testDescLong':
        'Questões geradas por IA que se adaptam às suas respostas. Seu nível CEFR exato será determinado automaticamente.',
    'orChooseManually': 'OU ESCOLHA MANUALMENTE',
    'selectYourLevel': 'Selecione seu Nível',
    'pleaseValidateKey': '⚠ Por favor, valide sua chave API primeiro.',
    'pleaseEnterKey': 'Por favor, insira sua chave API.',
    'goodMorning': 'Bom Dia',
    'goodAfternoon': 'Boa Tarde',
    'goodEvening': 'Boa Noite',
    'lateSession': 'Pronto para uma sessão noturna?',
    'letsPractice': 'Vamos praticar',
    'youAreAtLevel': 'Você está no nível',
    'change': 'Alterar',
    'whatToTalkAbout': 'Sobre o que você gostaria de falar?',
    'startLearning': 'Começar a Aprender',
    'placementTest': 'Teste de Nivelamento',
    'question': 'Questão',
    'of': 'de',
    'generatingQuestion': 'Gerando questão…',
    'analyzingProficiency': 'Analisando sua proficiência…',
    'tryAgain': 'Tente Novamente',
    'submitGetResults': 'Enviar e Obter Resultados',
    'nextQuestion': 'Próxima Questão →',
    'yourLevel': 'Seu Nível',
    'correct': 'corretas',
    'startLearningArrow': 'Começar a Aprender →',
    'typeAnswer': 'Digite sua resposta…',
    'submit': 'Enviar',
    'feedback': 'Feedback',
    'examples': 'Exemplos e Expressões',
    'translate': 'Traduzir',
    'translation': 'Tradução',
    'proficiency': 'PROFICIÊNCIA',
    'changeLevel': 'Alterar Nível',
    'languages': 'IDIOMAS',
    'iSpeak': 'Meu idioma',
    'iWantToLearn': 'Quero aprender',
    'topics': 'TÓPICOS',
    'apiKeySetup': 'CHAVE API',
    'testAndSave': 'Testar e Salvar',
    'selectNativeLanguage': 'Que idioma você fala?',
    'selectNativeLanguageDesc': 'Sua interface mudará para este idioma.',
    'selectTargetLanguage': 'Que idioma você quer aprender?',
    'selectTargetLanguageDesc': 'Exercícios de IA serão gerados neste idioma.',
    'translateOrAnswer': 'Traduzir ou Responder',
    'topicLabel': 'Tópico',
    'configureApiKeyFirst': 'Por favor, configure sua chave API primeiro.',
    'aiLanguageTutor': 'Tutor de Idiomas IA',
    'couldNotOpenLink': 'Não foi possível abrir o link.',
  },
  // ─── Chinese ──────────────────────────────────────────────────────────────
  'zh': {
    'selectLanguage': '选择您的语言',
    'selectLanguageDesc': '选择您使用的语言\n以个性化您的体验。',
    'continue': '继续',
    'welcomeTo': '欢迎来到 Salearn',
    'setupApiKey': '设置您的 API 密钥，然后我们将确定您的\n语言水平以个性化体验。',
    'step1ApiKey': '第一步：API 密钥',
    'apiKeyVerified': 'API 密钥已验证',
    'apiKeyRequired': '需要以启用 AI 功能',
    'pasteApiKey': '在此粘贴您的 Gemini API 密钥…',
    'validateSave': '验证并保存',
    'ready': '✓ 就绪',
    'howToGetKey': '如何获取 API 密钥？',
    'helpStep1': '访问 Google AI Studio',
    'helpStep2': '使用您的 Google 账号登录',
    'helpStep3': '点击“创建 API 密钥”并复制',
    'playTutorial': '播放教程',
    'takeTest': '参加分级测试',
    'testDesc': '10道自适应选择题 · 约4分钟',
    'testDescLong': '适应您的回答的 AI 生成选择题。您的确切 CEFR 水平将被自动确定。',
    'orChooseManually': '或手动选择',
    'selectYourLevel': '选择您的水平',
    'pleaseValidateKey': '⚠ 请先验证您的 API 密钥。',
    'pleaseEnterKey': '请输入您的 API 密钥。',
    'goodMorning': '早上好',
    'goodAfternoon': '下午好',
    'goodEvening': '晚上好',
    'lateSession': '准备好熬夜学习了吗？',
    'letsPractice': "我们来练习吧",
    'youAreAtLevel': '您的水平是',
    'change': '更改',
    'whatToTalkAbout': '您想聊些什么？',
    'startLearning': '开始学习',
    'placementTest': '分级测试',
    'question': '问题',
    'of': '/',
    'generatingQuestion': '正在生成问题…',
    'analyzingProficiency': '正在分析您的水平…',
    'tryAgain': '重试',
    'submitGetResults': '提交并获取结果',
    'nextQuestion': '下一题 →',
    'yourLevel': '您的水平',
    'correct': '正确',
    'startLearningArrow': '开始学习 →',
    'typeAnswer': '输入您的回答…',
    'submit': '提交',
    'feedback': '反馈',
    'examples': '示例与表达',
    'translate': '翻译',
    'translation': '翻译结果',
    'proficiency': '熟练度',
    'changeLevel': '更改水平',
    'languages': '语言',
    'iSpeak': '我的语言',
    'iWantToLearn': '我想学习',
    'topics': '主题',
    'apiKeySetup': 'API 密钥',
    'testAndSave': '测试并保存',
    'selectNativeLanguage': '您说哪种语言？',
    'selectNativeLanguageDesc': '您的界面将切换为该语言。',
    'selectTargetLanguage': '您想学习哪种语言？',
    'selectTargetLanguageDesc': 'AI 练习将使用该语言生成。',
    'translateOrAnswer': '翻译或回答',
    'topicLabel': '主题',
    'configureApiKeyFirst': '请先配置您的 API 密钥。',
    'aiLanguageTutor': 'AI 语言导师',
    'couldNotOpenLink': '无法打开链接。',
  },
  // ─── Japanese ─────────────────────────────────────────────────────────────
  'ja': {
    'selectLanguage': '言語を選択',
    'selectLanguageDesc': '使用する言語を選択して\n体験をパーソナライズしてください。',
    'continue': '続行',
    'welcomeTo': 'Salearnへようこそ',
    'setupApiKey': 'APIキーを設定すると、体験をパーソナライズするための\nレベルが判定されます。',
    'step1ApiKey': 'ステップ1：APIキー',
    'apiKeyVerified': 'APIキーを確認しました',
    'apiKeyRequired': 'AI機能の利用に必要です',
    'pasteApiKey': 'Gemini APIキーをここに貼り付け…',
    'validateSave': '検証して保存',
    'ready': '✓ 準備完了',
    'howToGetKey': 'APIキーの取得方法は？',
    'helpStep1': 'Google AI Studioにアクセス',
    'helpStep2': 'Googleアカウントでログイン',
    'helpStep3': '「Create API Key」をクリックしてコピー',
    'playTutorial': 'チュートリアルを再生',
    'takeTest': 'レベルテストを受ける',
    'testDesc': '10の適応型選択問題 · 約4分',
    'testDescLong': '回答に合わせて適応するAI生成の選択問題。正確なCEFRレベルが自動的に判定されます。',
    'orChooseManually': 'または手動で選択',
    'selectYourLevel': 'レベルを選択',
    'pleaseValidateKey': '⚠ まずAPIキーを検証してください。',
    'pleaseEnterKey': 'APIキーを入力してください。',
    'goodMorning': 'おはようございます',
    'goodAfternoon': 'こんにちは',
    'goodEvening': 'こんばんは',
    'lateSession': '夜の学習を始めますか？',
    'letsPractice': "練習しましょう",
    'youAreAtLevel': 'あなたのレベルは',
    'change': '変更',
    'whatToTalkAbout': '何について話しますか？',
    'startLearning': '学習を開始',
    'placementTest': 'レベルテスト',
    'question': '質問',
    'of': '/',
    'generatingQuestion': '質問を作成中…',
    'analyzingProficiency': 'レベルを分析中…',
    'tryAgain': '再試行',
    'submitGetResults': '送信して結果を見る',
    'nextQuestion': '次の質問 →',
    'yourLevel': 'あなたのレベル',
    'correct': '正解',
    'startLearningArrow': '学習を開始 →',
    'typeAnswer': '回答を入力…',
    'submit': '送信',
    'feedback': 'フィードバック',
    'examples': '例と表現',
    'translate': '翻訳',
    'translation': '翻訳結果',
    'proficiency': '熟練度',
    'changeLevel': 'レベルを変更',
    'languages': '言語',
    'iSpeak': '私の言語',
    'iWantToLearn': '学びたい言語',
    'topics': 'トピック',
    'apiKeySetup': 'APIキー',
    'testAndSave': 'テストして保存',
    'selectNativeLanguage': 'どの言語を話しますか？',
    'selectNativeLanguageDesc': 'インターフェースがこの言語に切り替わります。',
    'selectTargetLanguage': 'どの言語を学びたいですか？',
    'selectTargetLanguageDesc': 'AIの練習問題はこの言語で作成されます。',
    'translateOrAnswer': '翻訳または回答',
    'topicLabel': 'トピック',
    'configureApiKeyFirst': 'まずAPIキーを設定してください。',
    'aiLanguageTutor': 'AI 言語チューター',
    'couldNotOpenLink': 'リンクを開けませんでした。',
  },
};

// ─── Native names for the language picker ─────────────────────────────────────
const Map<String, String> kLanguageNativeNames = {
  'ar': 'العربية',
  'en': 'English',
  'fr': 'Français',
  'es': 'Español',
  'de': 'Deutsch',
  'tr': 'Türkçe',
  'it': 'Italiano',
  'pt': 'Português',
  'zh': '中文',
  'ja': '日本語',
};

const Map<String, String> kLanguageFlags = {
  'ar': '🇸🇦',
  'en': '🇬🇧',
  'fr': '🇫🇷',
  'es': '🇪🇸',
  'de': '🇩🇪',
  'tr': '🇹🇷',
  'it': '🇮🇹',
  'pt': '🇵🇹',
  'zh': '🇨🇳',
  'ja': '🇯🇵',
};

/// Get a localized UI string. Falls back to English.
String t(String key, String langCode) {
  return _strings[langCode]?[key] ?? _strings['en']?[key] ?? key;
}

/// Convenience: gets a localized UI string using [context]'s locale via easy_localization.
String tr(BuildContext context, String key, {List<String>? args}) =>
    key.tr(args: args);

// ─── Localized Topic Names ──────────────────────────────────────────────────
const Map<String, Map<String, String>> _topicNames = {
  'en': {
    'Daily Conversations': 'Daily Conversations',
    'Movies & TV Shows': 'Movies & TV Shows',
    'Philosophy': 'Philosophy',
    'Vocabulary Drill': 'Vocabulary Drill',
    'Grammar Practice': 'Grammar Practice',
    'Science & Nature': 'Science & Nature',
    'Travel': 'Travel',
    'Technology': 'Technology',
    'Business & Finance': 'Business & Finance',
    'History & Culture': 'History & Culture',
    'Sports': 'Sports',
    'Food & Cooking': 'Food & Cooking',
    'Weather & Seasons': 'Weather & Seasons',
    'Health & Fitness': 'Health & Fitness',
    'Music & Arts': 'Music & Arts',
    'Fashion & Shopping': 'Fashion & Shopping',
    'Education & Learning': 'Education & Learning',
  },
  'ar': {
    'Daily Conversations': 'محادثات يومية',
    'Movies & TV Shows': 'أفلام ومسلسلات',
    'Philosophy': 'فلسفة',
    'Vocabulary Drill': 'تدريب المفردات',
    'Grammar Practice': 'تمارين القواعد',
    'Science & Nature': 'العلوم والطبيعة',
    'Travel': 'السفر',
    'Technology': 'التكنولوجيا',
    'Business & Finance': 'الأعمال والمال',
    'History & Culture': 'التاريخ والثقافة',
    'Sports': 'الرياضة',
    'Food & Cooking': 'الطعام والطبخ',
    'Weather & Seasons': 'الطقس والفصول',
    'Health & Fitness': 'الصحة واللياقة',
    'Music & Arts': 'الموسيقى والفنون',
    'Fashion & Shopping': 'الأزياء والتسوق',
    'Education & Learning': 'التعليم والتعلم',
  },
  'fr': {
    'Daily Conversations': 'Conversations quotidiennes',
    'Movies & TV Shows': 'Films et séries',
    'Philosophy': 'Philosophie',
    'Vocabulary Drill': 'Exercices de vocabulaire',
    'Grammar Practice': 'Pratique de grammaire',
    'Science & Nature': 'Sciences et nature',
    'Travel': 'Voyages',
    'Technology': 'Technologie',
    'Business & Finance': 'Affaires et finance',
    'History & Culture': 'Histoire et culture',
    'Sports': 'Sport',
    'Food & Cooking': 'Cuisine et recettes',
    'Weather & Seasons': 'Weather & Seasons',
    'Health & Fitness': 'Health & Fitness',
    'Music & Arts': 'Music & Arts',
    'Fashion & Shopping': 'Fashion & Shopping',
    'Education & Learning': 'Education & Learning',
  },
  'es': {
    'Daily Conversations': 'Conversaciones diarias',
    'Movies & TV Shows': 'Películas y series',
    'Philosophy': 'Filosofía',
    'Vocabulary Drill': 'Ejercicio de vocabulario',
    'Grammar Practice': 'Práctica de gramática',
    'Science & Nature': 'Ciencia y naturaleza',
    'Travel': 'Viajes',
    'Technology': 'Tecnología',
    'Business & Finance': 'Negocios y finanzas',
    'History & Culture': 'Historia y cultura',
    'Sports': 'Deportes',
    'Food & Cooking': 'Comida y cocina',
    'Weather & Seasons': 'Weather & Seasons',
    'Health & Fitness': 'Health & Fitness',
    'Music & Arts': 'Music & Arts',
    'Fashion & Shopping': 'Fashion & Shopping',
    'Education & Learning': 'Education & Learning',
  },
  'tr': {
    'Daily Conversations': 'Günlük konuşmalar',
    'Movies & TV Shows': 'Filmler ve diziler',
    'Philosophy': 'Felsefe',
    'Vocabulary Drill': 'Kelime alıştırması',
    'Grammar Practice': 'Dil bilgisi pratiği',
    'Science & Nature': 'Bilim ve doğa',
    'Travel': 'Seyahat',
    'Technology': 'Teknoloji',
    'Business & Finance': 'İş ve finans',
    'History & Culture': 'Tarih ve kültür',
    'Sports': 'Spor',
    'Food & Cooking': 'Yemek ve mutfak',
    'Weather & Seasons': 'Weather & Seasons',
    'Health & Fitness': 'Health & Fitness',
    'Music & Arts': 'Music & Arts',
    'Fashion & Shopping': 'Fashion & Shopping',
    'Education & Learning': 'Education & Learning',
  },
  'de': {
    'Daily Conversations': 'Alltagsgespräche',
    'Movies & TV Shows': 'Filme und Serien',
    'Philosophy': 'Philosophie',
    'Vocabulary Drill': 'Vokabeltraining',
    'Grammar Practice': 'Grammatikübung',
    'Science & Nature': 'Wissenschaft und Natur',
    'Travel': 'Reisen',
    'Technology': 'Technologie',
    'Business & Finance': 'Wirtschaft und Finanzen',
    'History & Culture': 'Geschichte und Kultur',
    'Sports': 'Sport',
    'Food & Cooking': 'Essen und Kochen',
    'Weather & Seasons': 'Weather & Seasons',
    'Health & Fitness': 'Health & Fitness',
    'Music & Arts': 'Music & Arts',
    'Fashion & Shopping': 'Fashion & Shopping',
    'Education & Learning': 'Education & Learning',
  },
  'it': {
    'Daily Conversations': 'Conversazioni quotidiane',
    'Movies & TV Shows': 'Film e serie TV',
    'Philosophy': 'Filosofia',
    'Vocabulary Drill': 'Esercizi di vocabolario',
    'Grammar Practice': 'Pratica grammaticale',
    'Science & Nature': 'Scienza e natura',
    'Travel': 'Viaggi',
    'Technology': 'Tecnologia',
    'Business & Finance': 'Affari e finanza',
    'History & Culture': 'Storia e cultura',
    'Sports': 'Sport',
    'Food & Cooking': 'Cibo e cucina',
    'Weather & Seasons': 'Weather & Seasons',
    'Health & Fitness': 'Health & Fitness',
    'Music & Arts': 'Music & Arts',
    'Fashion & Shopping': 'Fashion & Shopping',
    'Education & Learning': 'Education & Learning',
  },
  'pt': {
    'Daily Conversations': 'Conversas diárias',
    'Movies & TV Shows': 'Filmes e séries',
    'Philosophy': 'Filosofia',
    'Vocabulary Drill': 'Treino de vocabulário',
    'Grammar Practice': 'Prática de gramática',
    'Science & Nature': 'Ciência e natureza',
    'Travel': 'Viagens',
    'Technology': 'Tecnologia',
    'Business & Finance': 'Negócios e finanças',
    'History & Culture': 'História e cultura',
    'Sports': 'Esportes',
    'Food & Cooking': 'Comida e culinária',
    'Weather & Seasons': 'Weather & Seasons',
    'Health & Fitness': 'Health & Fitness',
    'Music & Arts': 'Music & Arts',
    'Fashion & Shopping': 'Fashion & Shopping',
    'Education & Learning': 'Education & Learning',
  },
  'zh': {
    'Daily Conversations': '日常对话',
    'Movies & TV Shows': '电影与电视剧',
    'Philosophy': '哲学',
    'Vocabulary Drill': '词汇练习',
    'Grammar Practice': '语法练习',
    'Science & Nature': '科学与自然',
    'Travel': '旅行',
    'Technology': '科技',
    'Business & Finance': '商业与金融',
    'History & Culture': '历史与文化',
    'Sports': '体育',
    'Food & Cooking': '美食与烹饪',
    'Weather & Seasons': 'Weather & Seasons',
    'Health & Fitness': 'Health & Fitness',
    'Music & Arts': 'Music & Arts',
    'Fashion & Shopping': 'Fashion & Shopping',
    'Education & Learning': 'Education & Learning',
  },
  'ja': {
    'Daily Conversations': '日常会話',
    'Movies & TV Shows': '映画とテレビ番組',
    'Philosophy': '哲学',
    'Vocabulary Drill': '語彙練習',
    'Grammar Practice': '文法練習',
    'Science & Nature': '科学と自然',
    'Travel': '旅行',
    'Technology': 'テクノロジー',
    'Business & Finance': 'ビジネスと金融',
    'History & Culture': '歴史と文化',
    'Sports': 'スポーツ',
    'Food & Cooking': '食べ物と料理',
    'Weather & Seasons': 'Weather & Seasons',
    'Health & Fitness': 'Health & Fitness',
    'Music & Arts': 'Music & Arts',
    'Fashion & Shopping': 'Fashion & Shopping',
    'Education & Learning': 'Education & Learning',
  },
};

/// Get a localized topic name. Falls back to English key (= original name).
String tTopic(String topicKey, String langCode) {
  return _topicNames[langCode]?[topicKey] ?? topicKey;
}

// ─── Localized Level Labels ─────────────────────────────────────────────────
const Map<String, Map<String, String>> _levelLabels = {
  'en': {
    'A1': 'Beginner',
    'A2': 'Elementary',
    'B1': 'Intermediate',
    'B2': 'Upper Intermediate',
    'C1': 'Advanced',
    'C2': 'Mastery',
  },
  'ar': {
    'A1': 'مبتدئ',
    'A2': 'أساسي',
    'B1': 'متوسط',
    'B2': 'فوق المتوسط',
    'C1': 'متقدم',
    'C2': 'إتقان',
  },
  'fr': {
    'A1': 'Débutant',
    'A2': 'Élémentaire',
    'B1': 'Intermédiaire',
    'B2': 'Intermédiaire avancé',
    'C1': 'Avancé',
    'C2': 'Maîtrise',
  },
  'es': {
    'A1': 'Principiante',
    'A2': 'Elemental',
    'B1': 'Intermedio',
    'B2': 'Intermedio alto',
    'C1': 'Avanzado',
    'C2': 'Dominio',
  },
  'tr': {
    'A1': 'Başlangıç',
    'A2': 'Temel',
    'B1': 'Orta',
    'B2': 'Orta üstü',
    'C1': 'İleri',
    'C2': 'Uzman',
  },
  'de': {
    'A1': 'Anfänger',
    'A2': 'Grundlagen',
    'B1': 'Mittelstufe',
    'B2': 'Obere Mittelstufe',
    'C1': 'Fortgeschritten',
    'C2': 'Kompetent',
  },
  'it': {
    'A1': 'Principiante',
    'A2': 'Elementare',
    'B1': 'Intermedio',
    'B2': 'Intermedio alto',
    'C1': 'Avanzato',
    'C2': 'Padronanza',
  },
  'pt': {
    'A1': 'Iniciante',
    'A2': 'Básico',
    'B1': 'Intermediário',
    'B2': 'Intermediário superior',
    'C1': 'Avançado',
    'C2': 'Fluente',
  },
  'zh': {
    'A1': '入门',
    'A2': '初级',
    'B1': '中级',
    'B2': '中高级',
    'C1': '高级',
    'C2': '精通',
  },
  'ja': {
    'A1': '入門',
    'A2': '初級',
    'B1': '中級',
    'B2': '中上級',
    'C1': '上級',
    'C2': 'マスター',
  },
};

const Map<String, Map<String, String>> _levelDescs = {
  'en': {
    'A1': 'Basic phrases and simple interactions',
    'A2': 'Routine tasks and familiar topics',
    'B1': 'Main points and everyday situations',
    'B2': 'Complex texts and abstract topics',
    'C1': 'Fluent expression and implicit meaning',
    'C2': 'Near-native precision and nuance',
  },
  'ar': {
    'A1': 'عبارات أساسية وتفاعلات بسيطة',
    'A2': 'مهام روتينية ومواضيع مألوفة',
    'B1': 'النقاط الرئيسية والمواقف اليومية',
    'B2': 'نصوص معقدة ومواضيع مجردة',
    'C1': 'تعبير طليق ومعانٍ ضمنية',
    'C2': 'دقة وتمييز قريبة من الناطق الأصلي',
  },
  'fr': {
    'A1': 'Phrases de base et interactions simples',
    'A2': 'Tâches courantes et sujets familiers',
    'B1': 'Points principaux et situations quotidiennes',
    'B2': 'Textes complexes et sujets abstraits',
    'C1': 'Expression fluide et sens implicite',
    'C2': 'Précision et nuance quasi natives',
  },
  'es': {
    'A1': 'Frases básicas e interacciones simples',
    'A2': 'Tareas rutinarias y temas familiares',
    'B1': 'Puntos principales y situaciones cotidianas',
    'B2': 'Textos complejos y temas abstractos',
    'C1': 'Expresión fluida y significado implícito',
    'C2': 'Precisión y matiz casi nativos',
  },
  'tr': {
    'A1': 'Temel ifadeler ve basit etkileşimler',
    'A2': 'Günlük görevler ve tanıdık konular',
    'B1': 'Ana noktalar ve günlük durumlar',
    'B2': 'Karmaşık metinler ve soyut konular',
    'C1': 'Akıcı ifade ve örtük anlam',
    'C2': 'Ana dile yakın hassasiyet ve nüans',
  },
  'de': {
    'A1': 'Grundlegende Phrasen und einfache Interaktionen',
    'A2': 'Routineaufgaben und vertraute Themen',
    'B1': 'Hauptpunkte und Alltagssituationen',
    'B2': 'Komplexe Texte und abstrakte Themen',
    'C1': 'Fließender Ausdruck und implizite Bedeutung',
    'C2': 'Nahezu muttersprachliche Präzision',
  },
  'it': {
    'A1': 'Frasi di base e interazioni semplici',
    'A2': 'Compiti di routine e argomenti familiari',
    'B1': 'Punti principali e situazioni quotidiane',
    'B2': 'Testi complessi e argomenti astratti',
    'C1': 'Espressione fluida e significato implicito',
    'C2': 'Precisione e sfumature quasi madrelingua',
  },
  'pt': {
    'A1': 'Frases básicas e interações simples',
    'A2': 'Tarefas rotineiras e tópicos familiares',
    'B1': 'Pontos principais e situações cotidianas',
    'B2': 'Textos complexos e tópicos abstratos',
    'C1': 'Expressão fluente e significado implícito',
    'C2': 'Precisão e nuances quase nativas',
  },
  'zh': {
    'A1': '基本短语和简单交流',
    'A2': '日常任务和熟悉主题',
    'B1': '要点和日常情境',
    'B2': '复杂文本和抽象主题',
    'C1': '流利表达和隐含意义',
    'C2': '近乎母语的精确度和细微差别',
  },
  'ja': {
    'A1': '基本的なフレーズと簡単なやり取り',
    'A2': '日常的なタスクと身近なトピック',
    'B1': '要点と日常的な状況',
    'B2': '複雑なテキストと抽象的なトピック',
    'C1': '流暢な表現と暗黙の意味',
    'C2': 'ネイティブに近い正確さとニュアンス',
  },
};

/// Get a localized level label. Falls back to English.
String tLevel(String levelCode, String langCode) {
  return _levelLabels[langCode]?[levelCode] ??
      _levelLabels['en']?[levelCode] ??
      levelCode;
}

/// Get a localized level description. Falls back to English.
String tLevelDesc(String levelCode, String langCode) {
  return _levelDescs[langCode]?[levelCode] ??
      _levelDescs['en']?[levelCode] ??
      '';
}
