// lib/ui_strings.dart
// Simple localization system keyed by language code.
// Falls back to English if a key or language is missing.

const Map<String, Map<String, String>> _strings = {
  // ─── English ──────────────────────────────────────────────────────────────
  'en': {
    'selectLanguage': 'Select Your Language',
    'selectLanguageDesc': 'Choose the language you speak\nto personalize your experience.',
    'continue': 'Continue',
    'welcomeTo': 'Welcome to Salearn',
    'setupApiKey': 'Set up your API key, then we\'ll find your\nlanguage level to personalize your experience.',
    'step1ApiKey': 'Step 1: API Key',
    'apiKeyVerified': 'API Key Verified',
    'apiKeyRequired': 'Required to power AI features',
    'pasteApiKey': 'Paste your Gemini API key…',
    'validateSave': 'Validate & Save',
    'ready': '✓ Ready',
    'howToGetKey': 'How to get your API Key?',
    'helpStep1': 'Visit Google AI Studio',
    'helpStep2': 'Log in with your Google account',
    'helpStep3': 'Click "Create API Key" and copy it',
    'playTutorial': 'Play Tutorial',
    'takeTest': 'Take the Placement Test',
    'testDesc': '5 adaptive MCQ questions · ~2 min',
    'testDescLong': 'AI-generated multiple choice questions that adapt to your answers. Your exact CEFR level will be determined automatically.',
    'orChooseManually': 'OR CHOOSE MANUALLY',
    'selectYourLevel': 'Select Your Level',
    'pleaseValidateKey': '⚠ Please validate your API key first.',
    'pleaseEnterKey': 'Please enter your API key.',
    // Dashboard
    'goodMorning': 'Good Morning',
    'goodAfternoon': 'Good Afternoon',
    'goodEvening': 'Good Evening',
    'lateSession': 'Ready for a late session?',
    'letsPractice': "Let's practice",
    'youAreAtLevel': 'You are at level',
    'change': 'Change',
    'whatToTalkAbout': 'What would you like to talk about?',
    'startLearning': 'Start Learning',
    // Test
    'placementTest': 'Placement Test',
    'question': 'Question',
    'of': 'of',
    'generatingQuestion': 'Generating question…',
    'analyzingProficiency': 'Analyzing your proficiency…',
    'tryAgain': 'Try Again',
    'submitGetResults': 'Submit & Get Results',
    'nextQuestion': 'Next Question →',
    'yourLevel': 'Your Level',
    'correct': 'correct',
    'startLearningArrow': 'Start Learning →',
    // Main
    'typeAnswer': 'Type your answer…',
    'submit': 'Submit',
    'feedback': 'Feedback',
    'examples': 'Examples & Expressions',
    'translate': 'Translate',
    'translation': 'Translation',
    // Drawer
    'proficiency': 'PROFICIENCY',
    'changeLevel': 'Change Level',
    'languages': 'LANGUAGES',
    'iSpeak': 'My language',
    'iWantToLearn': 'I want to learn',
    'topics': 'TOPICS',
    'apiKeySetup': 'API KEY',
    'testAndSave': 'Test & Save',
  },
  // ─── Arabic ───────────────────────────────────────────────────────────────
  'ar': {
    'selectLanguage': 'اختر لغتك',
    'selectLanguageDesc': 'اختر اللغة التي تتحدثها\nلتخصيص تجربتك.',
    'continue': 'متابعة',
    'welcomeTo': 'مرحبًا بك في Salearn',
    'setupApiKey': 'أدخل مفتاح API الخاص بك، ثم سنحدد\nمستوى لغتك لتخصيص تجربتك.',
    'step1ApiKey': 'الخطوة 1: مفتاح API',
    'apiKeyVerified': 'تم التحقق من المفتاح',
    'apiKeyRequired': 'مطلوب لتشغيل ميزات الذكاء الاصطناعي',
    'pasteApiKey': 'الصق مفتاح Gemini API هنا…',
    'validateSave': 'تحقق واحفظ',
    'ready': '✓ جاهز',
    'howToGetKey': 'كيف تحصل على مفتاح API؟',
    'helpStep1': 'زر Google AI Studio',
    'helpStep2': 'سجّل الدخول بحساب Google',
    'helpStep3': 'اضغط "إنشاء مفتاح API" وانسخه',
    'playTutorial': 'شاهد الشرح',
    'takeTest': 'خذ اختبار تحديد المستوى',
    'testDesc': '5 أسئلة تكيفية · ~2 دقيقة',
    'testDescLong': 'أسئلة اختيار من متعدد مولّدة بالذكاء الاصطناعي تتكيف مع إجاباتك. سيتم تحديد مستواك CEFR تلقائيًا.',
    'orChooseManually': 'أو اختر يدويًا',
    'selectYourLevel': 'اختر مستواك',
    'pleaseValidateKey': '⚠ يرجى التحقق من مفتاح API أولاً.',
    'pleaseEnterKey': 'يرجى إدخال مفتاح API.',
    'goodMorning': 'صباح الخير',
    'goodAfternoon': 'مساء الخير',
    'goodEvening': 'مساء الخير',
    'lateSession': 'جلسة متأخرة؟',
    'letsPractice': 'هيا نتمرن على',
    'youAreAtLevel': 'أنت في المستوى',
    'change': 'تغيير',
    'whatToTalkAbout': 'عن ماذا تريد التحدث؟',
    'startLearning': 'ابدأ التعلم',
    'placementTest': 'اختبار تحديد المستوى',
    'question': 'سؤال',
    'of': 'من',
    'generatingQuestion': 'جاري إنشاء السؤال…',
    'analyzingProficiency': 'جاري تحليل مستواك…',
    'tryAgain': 'حاول مجددًا',
    'submitGetResults': 'إرسال والنتائج',
    'nextQuestion': 'السؤال التالي →',
    'yourLevel': 'مستواك',
    'correct': 'صحيح',
    'startLearningArrow': 'ابدأ التعلم →',
    'typeAnswer': 'اكتب إجابتك…',
    'submit': 'إرسال',
    'feedback': 'التقييم',
    'examples': 'أمثلة وتعبيرات',
    'translate': 'ترجمة',
    'translation': 'ترجمة',
    'proficiency': 'المستوى',
    'changeLevel': 'تغيير المستوى',
    'languages': 'اللغات',
    'iSpeak': 'لغتي',
    'iWantToLearn': 'أريد تعلم',
    'topics': 'المواضيع',
    'apiKeySetup': 'مفتاح API',
    'testAndSave': 'اختبر واحفظ',
  },
  // ─── French ───────────────────────────────────────────────────────────────
  'fr': {
    'selectLanguage': 'Choisissez votre langue',
    'selectLanguageDesc': 'Choisissez la langue que vous parlez\npour personnaliser votre expérience.',
    'continue': 'Continuer',
    'welcomeTo': 'Bienvenue sur Salearn',
    'setupApiKey': 'Configurez votre clé API, puis nous trouverons\nvotre niveau pour personnaliser votre expérience.',
    'step1ApiKey': 'Étape 1 : Clé API',
    'apiKeyVerified': 'Clé API vérifiée',
    'apiKeyRequired': 'Nécessaire pour les fonctionnalités IA',
    'pasteApiKey': 'Collez votre clé API Gemini…',
    'validateSave': 'Valider et enregistrer',
    'ready': '✓ Prêt',
    'howToGetKey': 'Comment obtenir votre clé API ?',
    'helpStep1': 'Visitez Google AI Studio',
    'helpStep2': 'Connectez-vous avec votre compte Google',
    'helpStep3': 'Cliquez "Créer une clé API" et copiez-la',
    'playTutorial': 'Voir le tutoriel',
    'takeTest': 'Passer le test de placement',
    'testDesc': '5 questions adaptatives · ~2 min',
    'testDescLong': 'Questions à choix multiples générées par IA qui s\'adaptent à vos réponses. Votre niveau CECR sera déterminé automatiquement.',
    'orChooseManually': 'OU CHOISIR MANUELLEMENT',
    'selectYourLevel': 'Sélectionnez votre niveau',
    'pleaseValidateKey': '⚠ Veuillez d\'abord valider votre clé API.',
    'pleaseEnterKey': 'Veuillez entrer votre clé API.',
    'goodMorning': 'Bonjour',
    'goodAfternoon': 'Bon après-midi',
    'goodEvening': 'Bonsoir',
    'lateSession': 'Session tardive ?',
    'letsPractice': 'Pratiquons',
    'youAreAtLevel': 'Vous êtes au niveau',
    'change': 'Modifier',
    'whatToTalkAbout': 'De quoi voulez-vous parler ?',
    'startLearning': 'Commencer',
    'placementTest': 'Test de niveau',
    'question': 'Question',
    'of': 'sur',
    'generatingQuestion': 'Génération de la question…',
    'analyzingProficiency': 'Analyse de votre niveau…',
    'tryAgain': 'Réessayer',
    'submitGetResults': 'Soumettre et résultats',
    'nextQuestion': 'Question suivante →',
    'yourLevel': 'Votre niveau',
    'correct': 'correct',
    'startLearningArrow': 'Commencer →',
    'typeAnswer': 'Tapez votre réponse…',
    'submit': 'Envoyer',
    'feedback': 'Retour',
    'examples': 'Exemples et expressions',
    'translate': 'Traduire',
    'translation': 'Traduction',
    'proficiency': 'NIVEAU',
    'changeLevel': 'Changer le niveau',
    'languages': 'LANGUES',
    'iSpeak': 'Ma langue',
    'iWantToLearn': 'Je veux apprendre',
    'topics': 'SUJETS',
    'apiKeySetup': 'CLÉ API',
    'testAndSave': 'Tester et sauver',
  },
  // ─── Spanish ──────────────────────────────────────────────────────────────
  'es': {
    'selectLanguage': 'Elige tu idioma',
    'selectLanguageDesc': 'Elige el idioma que hablas\npara personalizar tu experiencia.',
    'continue': 'Continuar',
    'welcomeTo': 'Bienvenido a Salearn',
    'setupApiKey': 'Configura tu clave API, luego encontraremos\ntu nivel para personalizar tu experiencia.',
    'step1ApiKey': 'Paso 1: Clave API',
    'apiKeyVerified': 'Clave API verificada',
    'apiKeyRequired': 'Necesario para funciones de IA',
    'pasteApiKey': 'Pega tu clave API de Gemini…',
    'validateSave': 'Validar y guardar',
    'ready': '✓ Listo',
    'howToGetKey': '¿Cómo obtener tu clave API?',
    'helpStep1': 'Visita Google AI Studio',
    'helpStep2': 'Inicia sesión con tu cuenta de Google',
    'helpStep3': 'Haz clic en "Crear clave API" y cópiala',
    'playTutorial': 'Ver tutorial',
    'takeTest': 'Hacer el test de nivel',
    'testDesc': '5 preguntas adaptativas · ~2 min',
    'testDescLong': 'Preguntas de opción múltiple generadas por IA que se adaptan a tus respuestas. Tu nivel MCER se determinará automáticamente.',
    'orChooseManually': 'O ELEGIR MANUALMENTE',
    'selectYourLevel': 'Selecciona tu nivel',
    'pleaseValidateKey': '⚠ Por favor valida tu clave API primero.',
    'pleaseEnterKey': 'Por favor ingresa tu clave API.',
    'goodMorning': 'Buenos días',
    'goodAfternoon': 'Buenas tardes',
    'goodEvening': 'Buenas noches',
    'lateSession': '¿Sesión nocturna?',
    'letsPractice': 'Practiquemos',
    'youAreAtLevel': 'Estás en el nivel',
    'change': 'Cambiar',
    'whatToTalkAbout': '¿De qué quieres hablar?',
    'startLearning': 'Empezar',
    'placementTest': 'Test de nivel',
    'question': 'Pregunta',
    'of': 'de',
    'generatingQuestion': 'Generando pregunta…',
    'analyzingProficiency': 'Analizando tu nivel…',
    'tryAgain': 'Intentar de nuevo',
    'submitGetResults': 'Enviar y resultados',
    'nextQuestion': 'Siguiente →',
    'yourLevel': 'Tu nivel',
    'correct': 'correcto',
    'startLearningArrow': 'Empezar →',
    'typeAnswer': 'Escribe tu respuesta…',
    'submit': 'Enviar',
    'feedback': 'Comentarios',
    'examples': 'Ejemplos y expresiones',
    'translate': 'Traducir',
    'translation': 'Traducción',
    'proficiency': 'NIVEL',
    'changeLevel': 'Cambiar nivel',
    'languages': 'IDIOMAS',
    'iSpeak': 'Mi idioma',
    'iWantToLearn': 'Quiero aprender',
    'topics': 'TEMAS',
    'apiKeySetup': 'CLAVE API',
    'testAndSave': 'Probar y guardar',
  },
  // ─── Turkish ──────────────────────────────────────────────────────────────
  'tr': {
    'selectLanguage': 'Dilinizi seçin',
    'selectLanguageDesc': 'Deneyiminizi kişiselleştirmek için\nkonuştuğunuz dili seçin.',
    'continue': 'Devam',
    'welcomeTo': 'Salearn\'e hoş geldiniz',
    'setupApiKey': 'API anahtarınızı girin, ardından deneyiminizi\nkişiselleştirmek için seviyenizi belirleyelim.',
    'step1ApiKey': 'Adım 1: API Anahtarı',
    'apiKeyVerified': 'API Anahtarı doğrulandı',
    'apiKeyRequired': 'Yapay zeka özellikleri için gerekli',
    'pasteApiKey': 'Gemini API anahtarınızı yapıştırın…',
    'validateSave': 'Doğrula ve kaydet',
    'ready': '✓ Hazır',
    'howToGetKey': 'API anahtarı nasıl alınır?',
    'helpStep1': 'Google AI Studio\'yu ziyaret edin',
    'helpStep2': 'Google hesabınızla giriş yapın',
    'helpStep3': '"API Anahtarı Oluştur"a tıklayın ve kopyalayın',
    'playTutorial': 'Öğreticiyi izle',
    'takeTest': 'Seviye testini yapın',
    'testDesc': '5 uyarlanabilir soru · ~2 dk',
    'testDescLong': 'Cevaplarınıza göre uyarlanan yapay zeka üretimi çoktan seçmeli sorular. CEFR seviyeniz otomatik olarak belirlenecektir.',
    'orChooseManually': 'VEYA MANUEL SEÇİN',
    'selectYourLevel': 'Seviyenizi seçin',
    'pleaseValidateKey': '⚠ Lütfen önce API anahtarınızı doğrulayın.',
    'pleaseEnterKey': 'Lütfen API anahtarınızı girin.',
    'goodMorning': 'Günaydın',
    'goodAfternoon': 'İyi öğleden sonra',
    'goodEvening': 'İyi akşamlar',
    'lateSession': 'Gece çalışması mı?',
    'letsPractice': 'Hadi pratik yapalım',
    'youAreAtLevel': 'Seviyeniz',
    'change': 'Değiştir',
    'whatToTalkAbout': 'Ne hakkında konuşmak istersiniz?',
    'startLearning': 'Öğrenmeye başla',
    'placementTest': 'Seviye testi',
    'question': 'Soru',
    'of': '/',
    'generatingQuestion': 'Soru oluşturuluyor…',
    'analyzingProficiency': 'Seviyeniz analiz ediliyor…',
    'tryAgain': 'Tekrar dene',
    'submitGetResults': 'Gönder ve sonuçlar',
    'nextQuestion': 'Sonraki →',
    'yourLevel': 'Seviyeniz',
    'correct': 'doğru',
    'startLearningArrow': 'Başla →',
    'typeAnswer': 'Cevabınızı yazın…',
    'submit': 'Gönder',
    'feedback': 'Geri bildirim',
    'examples': 'Örnekler ve ifadeler',
    'translate': 'Çevir',
    'translation': 'Çeviri',
    'proficiency': 'SEVİYE',
    'changeLevel': 'Seviye değiştir',
    'languages': 'DİLLER',
    'iSpeak': 'Dilim',
    'iWantToLearn': 'Öğrenmek istiyorum',
    'topics': 'KONULAR',
    'apiKeySetup': 'API ANAHTARI',
    'testAndSave': 'Test et ve kaydet',
  },
  // ─── German ───────────────────────────────────────────────────────────────
  'de': {
    'selectLanguage': 'Wählen Sie Ihre Sprache',
    'selectLanguageDesc': 'Wählen Sie Ihre Sprache,\num Ihr Erlebnis zu personalisieren.',
    'continue': 'Weiter',
    'welcomeTo': 'Willkommen bei Salearn',
    'setupApiKey': 'Richten Sie Ihren API-Schlüssel ein, dann\nbestimmen wir Ihr Niveau.',
    'step1ApiKey': 'Schritt 1: API-Schlüssel',
    'apiKeyVerified': 'API-Schlüssel verifiziert',
    'apiKeyRequired': 'Erforderlich für KI-Funktionen',
    'pasteApiKey': 'Gemini API-Schlüssel einfügen…',
    'validateSave': 'Überprüfen & speichern',
    'ready': '✓ Bereit',
    'howToGetKey': 'Wie erhalte ich einen API-Schlüssel?',
    'helpStep1': 'Besuchen Sie Google AI Studio',
    'helpStep2': 'Melden Sie sich mit Google an',
    'helpStep3': 'Klicken Sie "API-Schlüssel erstellen" und kopieren',
    'playTutorial': 'Tutorial ansehen',
    'takeTest': 'Einstufungstest machen',
    'testDesc': '5 adaptive Fragen · ~2 Min',
    'testDescLong': 'KI-generierte Multiple-Choice-Fragen, die sich an Ihre Antworten anpassen. Ihr GER-Niveau wird automatisch bestimmt.',
    'orChooseManually': 'ODER MANUELL WÄHLEN',
    'selectYourLevel': 'Wählen Sie Ihr Niveau',
    'pleaseValidateKey': '⚠ Bitte überprüfen Sie zuerst Ihren API-Schlüssel.',
    'pleaseEnterKey': 'Bitte geben Sie Ihren API-Schlüssel ein.',
    'goodMorning': 'Guten Morgen',
    'goodAfternoon': 'Guten Tag',
    'goodEvening': 'Guten Abend',
    'lateSession': 'Späte Sitzung?',
    'letsPractice': 'Lass uns üben',
    'youAreAtLevel': 'Ihr Niveau ist',
    'change': 'Ändern',
    'whatToTalkAbout': 'Worüber möchten Sie sprechen?',
    'startLearning': 'Starten',
    'placementTest': 'Einstufungstest',
    'question': 'Frage',
    'of': 'von',
    'generatingQuestion': 'Frage wird generiert…',
    'analyzingProficiency': 'Analysiere Ihr Niveau…',
    'tryAgain': 'Erneut versuchen',
    'submitGetResults': 'Absenden & Ergebnisse',
    'nextQuestion': 'Nächste →',
    'yourLevel': 'Ihr Niveau',
    'correct': 'richtig',
    'startLearningArrow': 'Starten →',
    'typeAnswer': 'Antwort eingeben…',
    'submit': 'Senden',
    'feedback': 'Rückmeldung',
    'examples': 'Beispiele und Ausdrücke',
    'translate': 'Übersetzen',
    'translation': 'Übersetzung',
    'proficiency': 'NIVEAU',
    'changeLevel': 'Niveau ändern',
    'languages': 'SPRACHEN',
    'iSpeak': 'Meine Sprache',
    'iWantToLearn': 'Ich will lernen',
    'topics': 'THEMEN',
    'apiKeySetup': 'API-SCHLÜSSEL',
    'testAndSave': 'Testen & speichern',
  },
};

// ─── Native names for the language picker ─────────────────────────────────────
const Map<String, String> kLanguageNativeNames = {
  'ar': 'العربية',
  'en': 'English',
  'fr': 'Français',
  'es': 'Español',
  'de': 'Deutsch',
  'tr': 'Türkçe',
  'it': 'Italiano',
  'pt': 'Português',
  'zh': '中文',
  'ja': '日本語',
};

const Map<String, String> kLanguageFlags = {
  'ar': '🇸🇦',
  'en': '🇬🇧',
  'fr': '🇫🇷',
  'es': '🇪🇸',
  'de': '🇩🇪',
  'tr': '🇹🇷',
  'it': '🇮🇹',
  'pt': '🇵🇹',
  'zh': '🇨🇳',
  'ja': '🇯🇵',
};

/// Get a localized UI string. Falls back to English.
String t(String key, String langCode) {
  return _strings[langCode]?[key] ?? _strings['en']?[key] ?? key;
}
